//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGKNguyenTuanTu_63135967.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTY
    {
        public CONGTY()
        {
            this.DICHVUs = new HashSet<DICHVU>();
        }
    
        public int MaCT { get; set; }
        public string TenCT { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<DICHVU> DICHVUs { get; set; }
    }
}
