//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGKNguyenTuanTu_63135967.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public int MaDV { get; set; }
        public string TenDV { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<decimal> GiaDV { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> MaCT { get; set; }
    
        public virtual CONGTY CONGTY { get; set; }
    }
}
