CREATE DATABASE ThiGK_63135967;

USE ThiGK_63135967;

CREATE TABLE CONGTY
(
    MaCT INT PRIMARY KEY,
    TenCT NVARCHAR(255),
    DiaChi NVARCHAR(255)
);


CREATE TABLE DICHVU
(
    MaDV INT PRIMARY KEY,
    TenDV NVARCHAR(255),
    NgayCapNhat DATE,
    GiaDV DECIMAL(18, 3),
    AnhDaiDien NVARCHAR(255),
    MaCT INT,
    FOREIGN KEY (MaCT) REFERENCES CONGTY(MaCT)
);
